In [10]:
import numpy as np
from numpy import random 

#### 1. Create a numpy matrix of 3*2 float numbers, filled with ones. 

In [7]:
np.ones((3, 2), dtype="float")

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

#### 2. Given the X numpy array, create a new numpy array with the same shape and type as X, filled with sevens.

In [8]:
X = np.array([[[8, 3, 16, 2], [14, 7, 12, 0]], 
              [[3, 15, 0, 1], [2, 8, 3, -4]]], dtype='int8')

In [18]:
new_sevens = np.full_like(X, 7)
new_sevens


array([[[7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7]]], dtype=int8)

In [19]:
print(X.shape)
print(new_sevens.shape)

(2, 2, 4)
(2, 2, 4)


#### 3. Create a 3*3*3 numpy matrix filled with random integer values between 1 and 10.

In [15]:
random.randint(1, 11, size=(3, 3, 3))

array([[[ 1,  9,  2],
        [ 6,  9,  6],
        [ 8,  3, 10]],

       [[10,  6,  9],
        [ 7,  1,  5],
        [ 8,  9, 10]],

       [[ 9, 10,  1],
        [ 8, 10, 10],
        [ 3,  7,  9]]], dtype=int32)

#### 4. Create a numpy array with the odd numbers from 1 to 10, in descending order.


In [27]:
np.arange(9, 0, -2)

array([9, 7, 5, 3, 1])

#### 5. Create a 3*3 numpy matrix, filled with values ranging from 0 to 8.

In [30]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 6. Given the X numpy matrix, show the first two elements on the first two rows.


In [31]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [37]:
print(X[0, :2])
print(X[1, :2])

[1 2]
[5 6]


#### 7. Given the X numpy matrix, change the last item on the last row with a 0.


In [56]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[3, 3] = 0
print(X[3, 3])

0


In [55]:
print(X)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15  0]]


#### 8. Given the X numpy array, get numbers higher than the elements mean.


In [53]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
X.mean()

np.float64(0.9)

In [59]:
mask = X > X.mean()
X[mask]

array([ 8,  9, 10, 11, 12, 13, 14, 15])

#### 9. Given the X numpy matrix, get the odd numbers higher than the elements mean, but not including 15. 


In [88]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [89]:
flat_X = X.flatten()
flat_X

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [91]:
mean = X.mean()
mean

np.float64(8.5)

In [93]:
odd_numbers = np.arange(1, 16, 2)
odd_numbers

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [105]:
result = flat_X[(flat_X % 2 == 1) & (flat_X > mean) & (flat_X != 15)]
result


array([ 9, 11, 13])